apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              key: license_key
        - name: NEW_RELIC_APP_NAME
          value: "ResultApp"
        - name: NEW_RELIC_LOG
          value: "stdout"
        - name: NEW_RELIC_CONFIG_FILE
          value: "/newrelic/newrelic.js"
        volumeMounts:
        - name: newrelic
          mountPath: /newrelic
      volumes:
      - name: newrelic
        emptyDir: {}

