apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              key: license_key
        - name: NEW_RELIC_APP_NAME
          value: "VoteApp"
        - name: NEW_RELIC_LOG
          value: "stdout"
        - name: PYTHONPATH
          value: "/newrelic"
        - name: NEW_RELIC_CONFIG_FILE
          value: "/newrelic/newrelic.ini"
        volumeMounts:
        - name: newrelic
          mountPath: /newrelic
      volumes:
      - name: newrelic
        emptyDir: {}
